<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>fileTypes</key>
	<array>
		<string>ts2</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>include</key>
	<string>#typo_defined_properties</string>
	<key>keyEquivalent</key>
	<string>^~T</string>
	<key>name</key>
	<string>TypoScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\s*#.*</string>
			<key>name</key>
			<string>comment.line.number-sign</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*/.*</string>
			<key>name</key>
			<string>comment.line.slash-sign</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;\s+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.typoscript</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Prototype extension</string>
			<key>end</key>
			<string>(.+$)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.reference.prototype</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#typo_top_level_objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typo_stdWrap_all</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typo_defined_properties</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>=</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.operator</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>everything after the first equal sign</string>
			<key>end</key>
			<string>($)</string>
			<key>name</key>
			<string>string.interpolated.typoscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#typo_content_objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typo_defined_properties</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typo_constant</string>
				</dict>
				<dict>
					<key>include</key>
					<string>text.html.basic</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>('|")</string>
			<key>comment</key>
			<string>escaped string</string>
			<key>end</key>
			<string>('|")</string>
			<key>name</key>
			<string>support.other.multiline</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#typo_content_objects</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#typo_defined_properties</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#typo_top_level_objects</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typo_defined_properties</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#typo_constant</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>typo_constant</key>
		<dict>
			<key>match</key>
			<string>{\$.*}</string>
			<key>name</key>
			<string>variable.other.typoscript</string>
		</dict>
		<key>typo_content_objects</key>
		<dict>
			<key>comment</key>
			<string>all content objects and things defined by typo3 that sit on the right side of the equal sign</string>
			<key>match</key>
			<string>(TYPO3\.TypoScript:Case|TYPO3\.TypoScript:Collection|TYPO3\.TypoScript:Template|TYPO3\.TypoScript:Matcher|TYPO3\.TypoScript:Array|TYPO3\.TypoScript:Value||TYPO3\.Neos:Template|TYPO3\.Neos:Breadcrumb|TYPO3\.Neos:Menu|TYPO3\.Neos:MultiColumn|TYPO3\.Neos:Page|TYPO3\.Neos:Shortcut|TYPO3\.Neos:Plugin|TYPO3\.Neos:ContentCollection|TYPO3\.Neos:ContentCase||TYPO3\.Neos\.NodeTypes:Headline|TYPO3\.Neos\.NodeTypes:Html|TYPO3\.Neos\.NodeTypes:Image|TYPO3\.Neos\.NodeTypes:Menu|TYPO3\.Neos\.NodeTypes:Text|TYPO3\.Neos\.NodeTypes:TextWithImage|TYPO3\.Neos\.NodeTypes:TwoColumn|TYPO3\.Neos\.NodeTypes:ThreeColumn|TYPO3\.Neos\.NodeTypes:FourColumn||Page|Template|Breadcrumb|ContentCollection|Menu|Case|ContentCase)\b</string>
			<key>name</key>
			<string>support.constant.cobject.typoscript</string>
		</dict>
		<key>typo_defined_properties</key>
		<dict>
			<key>comment</key>
			<string>all basic properties</string>
			<key>match</key>
			<string>\b(templatePath|startingPoint|entryLevel|maxLevels)\b</string>
			<key>name</key>
			<string>variable.parameter</string>
		</dict>
		<key>typo_stdWrap_parseData</key>
		<dict>
			<key>comment</key>
			<string>parse data functions for stdWrap</string>
			<key>match</key>
			<string>\b(csConv|parseFunc|HTMLparser|split|prioriCalc|char|intval|date|strftime|age|case|bbytes|subtring|removeBadHTML|stripHtml|crop|rawUrlEncode|htmlSpecialCharacters|doubleBrTag|br|brTag|encapsLines|keywords|innerWrap|innerWrap2|fontTag|addParams|textStyle|tableStyle|filelink|postCObject|preCObject|wrapAlign|typolink|TCAselectItem|spaceBefore|spaceAfter|space|wrap|noTrimWrap|wrap2|wrap3|dataWrap|prepend|append|outerWrap|insertData|offsetWrap|postUserFunc|postUserFuncInt|prefixComment|editIcons|editPanel|debug|debugFunc|debugData)\b</string>
			<key>name</key>
			<string>support.function.typoscript</string>
		</dict>
		<key>typo_top_level_objects</key>
		<dict>
			<key>match</key>
			<string>\b(root|page)\b</string>
			<key>name</key>
			<string>variable.language.top_level.typoscript</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.typoscript2</string>
	<key>uuid</key>
	<string>21270492-e7f0-11e2-a247-26e750c8c401</string>
</dict>
</plist>
